Update Maria motto
indie-collective/website pull request #1
Opened 2019-10-25 14:10 UTC by feoche

2019-10-25 14:15 UTC, YoruNoHikage requested changes
I disagree with this.

"Мне нравится кулибиак"

2019-10-25 14:19 UTC, feoche commented
“Я люблю то, что ты делаешь!“ ?

2019-10-25 14:45 UTC, YoruNoHikage commented
лучше, но не то, что я ожидаю

2019-10-26 16:15 UTC, YoruNoHikage commented on index.html
> +          <p class="text-muted">“J'adore ce que vous faites !“</p>
```suggestion
          <p class="text-muted">En recherche de stage</p>
```

2019-10-30 17:38 UTC, YoruNoHikage commented on index.html
> +          <p class="text-muted">“J'adore ce que vous faites !“</p>
```suggestion
          <p class="text-muted">“J'adore ce que vous faites !“ et surtout les stages</p>
```

2020-05-30 10:52 UTC, YoruNoHikage commented
Update on this?

2020-05-30 11:53 UTC, feoche commented
Nope

2021-06-23 09:13 UTC, closed without merging

2021-06-24 18:30 UTC, engleek commented
Mais c'est quoi ce PR de la tristesse?

2021-06-25 09:25 UTC, YoruNoHikage commented
C'était une blague qui a trop duré.